apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.5.2
      helm:
        releaseName: alloy
        valueFiles:
          - $values/platform/grafana/values.yaml
    - repoURL: https://github.com/origoss/kubernetes-monitoring-platform.git
      targetRevision: feature/alloy
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
