apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.51.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/platform/loki/values.yaml
    - repoURL: https://github.com/origoss/kubernetes-monitoring-platform.git
      targetRevision: feature/loki
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
