# ============================================================
# Single common resource for all Loki components
# ============================================================
lokiCommonResources: &lokiCommonResources
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 300Mi
# ============================================================


deploymentMode: Distributed

global:
  extraEnvFrom:
    - secretRef:
        name: aws-s3-credentials

loki:
  extraArgs:
    - -config.expand-env=true
  structuredConfig:
    schema_config:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: index_
              period: 24h
    common:
      path_prefix: loki/
      storage:
        s3:
          bucket_name: ${BUCKET_NAME}
          region: eu-central-1
          insecure: true
          access_key_id: ${AWS_ACCESS_KEY_ID}
          endpoint: s3.amazonaws.com
          secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    ruler:
      storage:
        type: s3
        s3:
          key_prefix: ruler
  storage:
    type: s3
    bucketNames:
      chunks: ${BUCKET_NAME}
      ruler: ${BUCKET_NAME}
      admin: ${BUCKET_NAME}
  querier:
    max_concurrent: 2



minio:
  resources: *lokiCommonResources
  enabled: false

monitoring:
  selfMonitoring:
    grafanaAgent:
      resources: *lokiCommonResources
  serviceMonitor:
    enabled: true




# ============================================================
# Apply the same resources to all components
# ============================================================

lokiCanary:
  resources: *lokiCommonResources

adminApi:
  resources: *lokiCommonResources

gateway:
  resources: *lokiCommonResources

enterpriseGateway:
  resources: *lokiCommonResources

singleBinary:
  resources: *lokiCommonResources

write:
  resources: *lokiCommonResources

read:
  resources: *lokiCommonResources

backend:
  resources: *lokiCommonResources

ingester:
  resources: *lokiCommonResources

distributor:
  resources: *lokiCommonResources

# querier:
#   resources: *lokiCommonResources

queryFrontend:
  resources: *lokiCommonResources

queryScheduler:
  resources: *lokiCommonResources

indexGateway:
  resources: *lokiCommonResources

compactor:
  resources: *lokiCommonResources

bloomGateway:
  resources: *lokiCommonResources

bloomPlanner:
  resources: *lokiCommonResources

bloomBuilder:
  resources: *lokiCommonResources

patternIngester:
  resources: *lokiCommonResources

ruler:
  resources: *lokiCommonResources

overridesExporter:
  resources: *lokiCommonResources

memcachedExporter:
  resources: *lokiCommonResources

resultsCache:
  resources: *lokiCommonResources

chunksCache:
  resources: *lokiCommonResources
  l2:
    resources: *lokiCommonResources

sidecar:
  resources: *lokiCommonResources


tableManager:
  resources: *lokiCommonResources
