deploymentMode: Distributed

global:
  extraEnvFrom:
    - secretRef:
        name: aws-s3-credentials

loki:
  extraArgs:
    - -config.expand-env=true
  structuredConfig:
    schema_config:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: index_
              period: 24h
    common:
      path_prefix: loki/
      storage:
        s3:
          bucket_name: ${BUCKET_NAME}
          region: eu-central-1
          insecure: true
          access_key_id: ${AWS_ACCESS_KEY_ID}
          endpoint: s3.amazonaws.com
          secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    ruler:
      storage:
        type: s3
        s3:
          key_prefix: ruler
  storage:
    type: s3
    bucketNames:
      chunks: ${BUCKET_NAME}
      ruler: ${BUCKET_NAME}
      admin: ${BUCKET_NAME}


minio:
  enabled: false

monitoring:
  serviceMonitor:
    enabled: true
