apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.18.0
      helm:
        releaseName: sealed-secrets
        valueFiles:
          - $values/platform/sealed-secrets/values.yaml
    - repoURL: 'https://github.com/origoss/kubernetes-monitoring-platform.git'
      targetRevision: 'feature/sealed-secrets'
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true