apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://argoproj.github.io/argo-helm'
      chart: argo-cd
      targetRevision: 9.3.7
      helm:
        releaseName: argo-cd
        valueFiles:
          - $values/platform/argocd/values.yaml
    - repoURL: 'https://github.com/origoss/kubernetes-monitoring-platform.git'
      targetRevision: 'feature/loki'
      path: platform
      directory:
        recurse: true
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true