global:
  extraEnvFrom:
    - secretRef:
        name: aws-s3-credentials
  podAnnotations:
    bucketSecretVersion: "0"

minio:
  enabled: false

buckets:
  createBucketsJob:
    enabled: false
mimir:
  structuredConfig:
    blocks_storage:
      backend: s3
      storage_prefix: mimirBlocks
      s3:
        bucket_name: ${BUCKET_NAME}
        region: eu-central-1
        insecure: true
        access_key_id: ${AWS_ACCESS_KEY_ID}
        endpoint: s3.amazonaws.com
        secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    alertmanager_storage:
      backend: s3
      storage_prefix: mimirAlertmanager
      s3:
        bucket_name: ${BUCKET_NAME}
        region: eu-central-1
        insecure: true
        access_key_id: ${AWS_ACCESS_KEY_ID}
        endpoint: s3.amazonaws.com
        secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    ruler_storage:
      backend: s3
      storage_prefix: mimirRuler
      s3:
        bucket_name: ${BUCKET_NAME}
        region: eu-central-1
        insecure: true
        access_key_id: ${AWS_ACCESS_KEY_ID}
        endpoint: s3.amazonaws.com
        secret_access_key: ${AWS_SECRET_ACCESS_KEY}
metaMonitoring:
  serviceMonitor:
    enabled: true

# ============================================================
# Centralized resource configuration for all Mimir components
# ============================================================

mimirCommonResources: &mimirCommonResources
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 300m
    memory: 400Mi

# =========================
# Core Mimir Components
# =========================

alertmanager:
  resources: *mimirCommonResources

ingester:
  resources: *mimirCommonResources

distributor:
  resources: *mimirCommonResources

overrides_exporter:
  resources: *mimirCommonResources

ruler:
  resources: *mimirCommonResources

ruler_querier:
  resources: *mimirCommonResources

ruler_querier_frontend:
  resources: *mimirCommonResources

ruler_querier_scheduler:
  resources: *mimirCommonResources

querier:
  resources: *mimirCommonResources

querier_frontend:
  resources: *mimirCommonResources

querier_scheduler:
  resources: *mimirCommonResources

store_gateway:
  resources: *mimirCommonResources

compactor:
  resources: *mimirCommonResources

kafka:
  resources: *mimirCommonResources